### ISSUE TITLE
Support for Vulkan/Metal

### ISSUE THREAD

**Issue by daniol** [skiselkov/librain#21]
librain does not support the new rendering engine Vulkan/Metal.

Source:
https://www.x-plane.com/kb/x-plane-11-50-release-notes/#Known_Addon_Issues

**Comment by skiselkov** [comment]
I'm aware of it.

**Comment by daniol** [comment]
Nice, thanks :thumbsup:

**Comment by dilshaan123** [comment]
When will librain plugin will work on Vulkan is there any update ???

**Comment by firstpon** [comment]
Are you currently working on making it compatible with vulkan? Or is it never gonna compatible with vulkan? Thank you.
