### ISSUE TITLE
come si installa librain?

### ISSUE THREAD

**Issue by andreaXX** [skiselkov/librain#22]
cioè si so muovere script, cambiare suoni di un aereo, ma oddio sono nuovo, ma sto passando 3 ore a capire il primo passaggio, non esiste nessun video . dunque sono in difficolta, non so neanche dove chiedere.... nella speranza di risposta mi consulto con voi,           PS. riuscireste a farte un breve video,sennò va bene anche una spiegazione verso un'ignorante

**Comment by skiselkov** [comment]
Please use English. Also, librain isn't something you install as an end user. It needs to be integrated with the aircraft by the developer.

**Comment by andreaXX** [comment]
Ok, so have to assign me a file?

**Comment by andreaXX** [comment]
Usually I use a B737-800 zibo
