### ISSUE TITLE
Librain / Vulcan Compatibility 

### ISSUE THREAD

**Issue by TheAustralianAviator** [skiselkov/librain#23]
Hey guy's is there any plans to implement compatibility for Vulcan with your Librain plugin ?

**Comment by skiselkov** [comment]
I plan on working on this. The new 11.50 rendering APIs *should* allow me to do it, but I can't guarantee it.

**Comment by TheAustralianAviator** [comment]
No worry's brother, thankyou for your fast reply and all the hard work you have done, especially when it comes to Better Pushback 😎

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dilshaan123** [comment]
Hello, how’s your work going on with librain functionality with Vulkan, any luck will you able to pull it off . 
Thanks it awesome .

**Comment by crazytimtimtim** [comment]
@skiselkov Are you still planning on getting this working?

**Comment by AlaistairP** [comment]
@skiselkov Hey! Any progress on getting this to work with Vulkan???

**Comment by crazytimtimtim** [comment]
rip

**Comment by AlaistairP** [comment]
Damn lmaooo, so no plans then?
