### ISSUE TITLE
Compiler Errors: Symbol cannot be resolved in C++

### ISSUE THREAD

**Issue by subabrain** [skiselkov/librain#26]
Hi there,

i really like your work! 

but i have an compiler error - as the following (its in german - in english it is like Symbol cannot be resolved in C++):
```

1>Hello-World-SDK-3.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "obj8_parse" in Funktion "XPluginStart".
1>Hello-World-SDK-3.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "librain_init" in Funktion "XPluginStart".
1>Hello-World-SDK-3.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "librain_fini" in Funktion "XPluginStart".
1>Hello-World-SDK-3.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "librain_draw_prepare" in Funktion ""int __cdecl draw_rain_effects(int,int,void *)" (?draw_rain_effects@@YAHHHPEAX@Z)".
1>Hello-World-SDK-3.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "librain_draw_exec" in Funktion ""int __cdecl draw_rain_effects(int,int,void *)" (?draw_rain_effects@@YAHHHPEAX@Z)".
1>Hello-World-SDK-3.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "librain_draw_finish" in Funktion ""int __cdecl draw_rain_effects(int,int,void *)" (?draw_rain_effects@@YAHHHPEAX@Z)".
1>Hello-World-SDK-3.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "librain_set_debug_draw" in Funktion "XPluginStart".

```

Thank you very much for help :)

Greetings
Robert

**Comment by subabrain** [comment]
okay ... i got it - was my problem ... :/

**Comment by subabrain** [comment]
sorry - its not fixed ... same errors above ...

**Comment by subabrain** [comment]
please help :)

**Comment by subabrain** [comment]
hmm okay ... i think i havent linked the nessacery dependencies :)
- so i close this Thread with one thing:

Please make a detailed Tutorial on compiling alle the libs and so on - thx!

**Comment by skiselkov** [comment]
Sorry for not getting to this sooner, was super busy. Glad you got it sorted.
The issue is your plugin build wasn't linking the built static library. The fact that you were missing references to librain_draw_prepare and similar (which are symbols exported from librain) means you weren't linking with it in your project.
